baseURL = 'https://dpi0.github.io'
languageCode = 'en-us'
title = 'echo'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

# to change the syntax highlight theme: https://makewithhugo.com/syntax-hightlight-color/

[params]
description = "a reflection in the sea of internet"
dark = "on"
highlight = true

[menu]
# [[menu.main]]
# identifier = "posts"
# name = "posts"
# title = "posts"
# url = "/"
# weight = 10

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 20

[permalinks]
posts = "/:title/"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.HTML]
[outputFormats.HTML.mediaTypes]
"text/html" = ["html"]
"text/javascript" = ["js"]
